language: node_js
node_js:
- '13'
sudo: required
os: linux
dist: bionic
addons:
  chrome: stable
  sonarcloud:
    organization: "$SONAR_KEY"
    token: "$SONAR_TOKEN"

branches:
  only:
  - main
  - develop
  - /^pbi-.*$/
cache: npm
install:
  - cd website/
  - npm ci
script: skip
jobs:
  include:
  - stage: test
    name: Run Tests
    if: NOT(tag IS present) AND NOT(branch =~ /^pbi-.*$/)
    script:
    - npm run test
    - sonar-scanner -X
  - stage: test
    name: Run linter
    if: NOT(tag IS present) AND NOT(branch =~ /^pbi-.*$/)
    script:
    - npm run lint
  - stage: deploy
    name: Deploy to GitHub Pages
    if: branch = main AND NOT(type = pull_request)
    script:
    - npm run build -- --output-hashing=none --base-href=/scimaps/
    - cp dist/scimaps/index.html dist/scimaps/404.html
    - touch dist/scimaps/.nojekyll
    - npm run compodoc
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: false
      local-dir: website/dist/scimaps
      on:
        branch: main
  - stage: deploy
    name: Deploy Staging Version
    if: branch = develop AND NOT(type = pull_request)
    script:
    - npm run build -- --output-hashing=none --base-href=/
    - cp dist/scimaps/index.html dist/scimaps/404.html
    - touch dist/scimaps/.nojekyll
    - npm run compodoc
    deploy:
      provider: pages
      target-branch: staging
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: false
      local-dir: website/dist/scimaps
      on:
        branch: develop
  - stage: deploy
    name: Deploy Preview for PRs
    if: branch =~ /^pbi-.*$/ AND NOT(type = pull_request)
    script:
    - npm run build -- --output-hashing=none --base-href=/
    deploy:
      provider: netlify
      skip-cleanup: true
      site: "$NETLIFY_SITE_ID"
      auth: "$NETLIFY_TOKEN"
      dir: website/dist/scimaps
      edge: true
      on:
        all_branches: true

notifications:
  slack:
    secure: kmHjR6duu+E+c+JEBLjECE5mSboVOrz599dOubVU7eqwVNUGvbe3YDGIKAc0S6akqsW0q9bVUWM2Zi+J4ROHrlMi1A+VQRJAW+2DG+6wu8fmdZiA0u/fK2w9IMRPFDDk80mMZN7TzSPMu5nRv6UGbVqpNeqRWotd2XtyLOu3+KRYKggUjKKz5D3oiYYGaHZWj6foDG7u42q33RQ55LlWff0GmAUuYVSfOUlxAYevOTuV9QF8NfFRnlQAfIYucM9177dd9cfWUdRgWPL7VGDUrANF2NtrfTUcWMM/zl6Vk7KMTxcCr1Oy0osxPE4DlpD8Mdz+i54tqKtcopJirBUnogZx+6MoMqMpTu7mU9pmB1H5rhAqlddYUMxiiyUvAvsScm3G5tY7azvqB0i6qalveTXuZWTa3CZUKHHTkDaDd0tnCvnLqWUaxZ2TeS//67q4EvreTfIdD4hD4phXjqfS+x0Ha8w7MpjwNln651svxsnpv+Ak6ET8N/NVRY61LhzAocMHitqMZMycTgyf8l5rciUtWE2cIuDiH86SBF+KeDYnoCCBwN8qXUTktVie37PeBX2drO84wNc8tmzjpIguXyCQUCBN/t0BodC4BIH+/oasfsYtKpXj6LQaV4/brf+t+hZX2FYssS44UZAKn3CQ92Mp7YurngUMHBqaMC6wPu4=
