collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: blog/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
  - name: book
    label: Book
    folder: content/book
    path: "{{slug}}/README"
    create: true
    slug: "{{slug}}"
    preview_path: book/{{slug}}
    media_folder: ''
    public_folder: ''
    fields:
      - { name: title, label: Title }
      - { name: author, label: Author }
      - { name: publisher, label: Publisher }
      - { name: pdfLink, label: PDF Link }
      - { name: amazonLink, label: Amazon Link }
      - { name: book_image, label: Book Image, widget: image }
      - { name: body, label: Abstract, widget: markdown }

backend:
  name: github
  repo: cns-iu/scimaps
  branch: pbi-cms-setup

# We'll switch to editorial workflow when we move closer to production
# publish_mode: editorial_workflow

media_folder: content/images/uploads
public_folder: /assets/images/uploads
site_url: https://dev.scimaps.org
display_url: https://dev.scimaps.org

logo_url: http://scimaps.org/images/global/ps_logo.png

show_preview_links: true
