name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm ci for content-migrator
        run: npm ci
        working-directory: content-migrator
      - run: npm run job
        working-directory: content-migrator
      - name: npm ci for website
        run: npm ci
        working-directory: website
      - run: npm run build -- --output-hashing=none --base-href=/
        working-directory: website
      - run: cp -r admin website/dist/scimaps
        working-directory: '.'
      - name: Setup Netlify files
        working-directory: website
        run: |
          echo '/* /index.html 200' > dist/scimaps/_redirects

      - name: Publish
        id: deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir="website/dist/scimaps"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Create Deploy Comment
        uses: ./.github/actions/deploy-comment
        with:
          deploy-url: ${{steps.deploy.outputs.NETLIFY_URL}}
