name: 'Staging Build'

on:
  workflow_run:
    workflows: ['Tests']
    branches: ['develop']
    types:
      - completed

jobs:
  deploy:
    name: 'Deploy'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm ci for content-migrator
        run: npm ci
        working-directory: content-migrator
      - run: npm run job
        working-directory: content-migrator
      - name: npm ci for website
        run: npm ci
        working-directory: website
      - run: npm run build -- --output-hashing=none --base-href=/
        working-directory: website
      - run: cp -r admin website/dist/scimaps
        working-directory: '.'
      - name: Setup GitHub Pages files
        working-directory: website
        run: |
          cp dist/scimaps/index.html dist/scimaps/404.html
          touch dist/scimaps/.nojekyll
      - name: Setup Netlify files
        working-directory: website
        run: |
          echo '/* /index.html 200' > dist/scimaps/_redirects

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist/scimaps
          publish_branch: staging
          commit_message: "Staging deploy -- ${{ github.event.head_commit.message }}"

      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Staging deploy to Netlify"
          NETLIFY_DEPLOY_TO_PROD: true
          build_command: false
          build_directory: website/dist/scimaps
